# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html

run:
  prefix: "ac_dc_vre_dstbtn_tnspt_heat_bmss_indstr_meth_dac_gasnet"
  shared_resources:
    policy: true
  use_shadow_directory: true

scenario:
  clusters: [2]

countries: ["DE", "CH"]

co2_budget:
  2050: 0

electricity:
  renewable_carriers: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, hydro]
  extendable_carriers:
    Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc]
  estimate_renewable_capacities:
    enable: false
  transmission_limit: c1.25

transmission_projects:
  enable: true
  include:
    tyndp2020: true

pypsa_eur:
  Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, ror]
  StorageUnit: [PHS, hydro]
  Link: [DC]
  Line: [AC]

clustering:
  temporal:
    resolution_sector: 24H  # limit of diurnal storage (Mai, 2022)

sector:
  transport: true

  heating: true
  district_heating:
    potential: 0.6
  time_dep_hp_cop: true

  biomass: true

  industry: true # only works because of code changes (remove once PR accepted)
  ammonia: false # NB. industrial/fertiliser demand for ammonia counted using H2 and elec. demand
  SMR: false # green H2 only
  SMR_cc: false
  methanation: true

  fossil_fuels: false # TODO: change to only supply methane for gas CCGT_CC
  gas_network: true

  dac: true
  co2_network: false # true

  H2_network: false # true
  H2_retrofit: false # true

  electricity_transmission_grid: true
  electricity_distribution_grid: true
