# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html

run:
  prefix: "ac_dc_vre_dstbtn_tnspt_heat_indstr_bmss_ccgt_gas"
  shared_resources:
    policy: true
  use_shadow_directory: true

scenario:
  clusters: [3]

countries: ["DE", "CH"]

electricity:
  renewable_carriers: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, hydro]
  extendable_carriers:
    Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc]
  estimate_renewable_capacities:
    enable: false
  transmission_limit: c1.25

transmission_projects:
  enable: true
  include:
    tyndp2020: true

pypsa_eur:
  Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, ror]
  StorageUnit: [PHS, hydro]
  Link: [DC]
  Line: [AC]

clustering:
  temporal:
    resolution_sector: 24H  # limit of diurnal storage (Mai, 2022)

sector:
  transport: true

  heating: true
  district_heating:
    potential: 0.6
  time_dep_hp_cop: true

  industry: true
  biomass: true
  conventional_generation: {CCGT: gas} # required for industry (to create EU gas bus)

  dac: false
  electricity_transmission_grid: true
  electricity_distribution_grid: true
